services:
  proxy:
    image: nginx:1.21.3-alpine
    container_name: lff-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./api-lff.conf:/etc/nginx/conf.d/api-lff.conf
      - ./web-lff.conf:/etc/nginx/conf.d/web-lff.conf

    networks:
      - lafacturefacile-network

networks:
  lafacturefacile-network:
    external: true
    name: lafacturefacile-network