services:
  proxy:
    image: nginx:1.27.3-alpine3.20-perl
    container_name: lff-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./api-lff.conf:/etc/nginx/conf.d/api-lff.conf
      - ./web-lff.conf:/etc/nginx/conf.d/web-lff.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
    networks:
      - lafacturefacile-network
networks:
  lafacturefacile-network:
    external: true
    name: lafacturefacile-network
