name: deploy lff proxy
on: [push]
env:
  IMAGE: lff-proxy
  VERSION: 0.0.1
jobs:
  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
    - name: execute commands
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          mkdir /opt/applications/lff/${{env.IMAGE}}
          ls -al /opt/applications/lff
  run-container:
    name: run container
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps:
      - name: cloner le repertoire
        uses: actions/checkout@master
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            port: 22
            source: "compose.yml,api-lff.conf,web-lff.conf"
            target: /opt/applications/lff/${{env.IMAGE}}
      - name: execute commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker-compose -f /opt/applications/lff/${{env.IMAGE}}/compose.yml up -d
            docker restart ${{env.IMAGES}}